### ISSUE TITLE
Two columns on mobile

### ISSUE THREAD

**Issue by rungulus** [runguszone/roosterteeth-archival-website#17]
Should be one, probably just need to bump `col` size up one but I'm not home so this is a reminder for me

**Comment by rungulus** [comment]
it is not as simple as that :(

investigating

**Comment by Anthony-P0** [comment]
Hi, I had a look at your pull-request solution and since it seems to change it to one column even when not on mobile. I thought I'd just provide you with another option, if that's okay? You could try using JavaScript to change the col size in the div tag as the screen is changed.

For example adding this script to the ArchiveList.astro page would dynamically change the class used:

`<script>
  function adjustColumnClass() {
    const archCols = document.querySelectorAll('.archCol');
    archCols.forEach(archCol => {
      if (window.innerWidth <= 600) { // Adjust 600 to your mobile breakpoint
        archCol.classList.remove('col-6');
        archCol.classList.add('col-12');
      } else {
        archCol.classList.remove('col-12');
        archCol.classList.add('col-6');
      }
    });
  }

  // Run initially and add event listener for resizing
  adjustColumnClass();
  window.addEventListener('resize', adjustColumnClass);
</script>`

And all you'd need to do is put `archCol`  in the div class tag.

`          <div class="archCol col-6 pb-2">
            <div class="frostedglass container" id={archive.category}>
              <p class="fs-2 runguszone mb-n">{archive.category}</p>
              <ul>
                {archive.links.map((link) => (
                  <li>
                    <a class="alert-link runguszone" href={link.url}>{link.name}</a>
                  </li>
                ))}
              </ul>
            </div>
          </div>  `

Which should allow for two columns on large screens, and one on small screens. Sorry if this is uneeded, just seems like not much has happened in the last month, so I thought I'd provide a possible solution if you wanted it, not necessary to use though.

**Comment by rungulus** [comment]
Thanks! This works good enough for our uses so I will go ahead and patch it in. Thanks for the assist!
